# Generated by Django 3.2 on 2023-03-03 20:24

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[api.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
