# Generated by Django 3.2 on 2023-03-03 21:31

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже зарегистирован!'}, max_length=150, unique=True, validators=[api.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
