# Generated by Django 3.2 on 2023-03-03 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20230303_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, error_messages={'validators': 'Проверьте год'}, null=True, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
