# Generated by Django 3.2 on 2023-03-05 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, error_messages={'validators': 'Проверьте год'}, null=True, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
