# Generated by Django 3.2 on 2023-03-05 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20230305_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, error_messages={'validators': 'Проверьте год'}, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
