# Generated by Django 3.2 on 2023-03-06 10:21

import django.core.validators
from django.db import migrations, models
import titles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, error_messages={'validators': 'Проверьте год'}, null=True, validators=[django.core.validators.MinValueValidator(0), titles.validators.year_validator]),
        ),
    ]
