# Generated by Django 3.2 on 2023-03-02 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_unique_author_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите оценку от 1 до 10!'), django.core.validators.MaxValueValidator(10, message='Введите оценку от 1 до 10!')]),
        ),
    ]
