# Generated by Django 3.2 on 2023-03-04 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_auto_20230303_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': '%(app_label)s_%(class)s_rewiews', 'verbose_name_plural': ('Комментарии',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': '%(app_label)s_%(class)s_rewiews', 'verbose_name_plural': ('Отзывы',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_comment_rewiews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_review_rewiews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Введите оценку от 1 до 10!'), django.core.validators.MaxValueValidator(10, message='Введите оценку от 1 до 10!')], verbose_name='Оценка произведения'),
        ),
    ]
